version: '3.7'

services:
  node:
    container_name: node
    build: .
    ports:
      - "3000:3000"
  
  python:
    image: python
    tty: true
    container_name: python
    volumes:
      - ./app:/scripts
    networks:
      - test-tutorial      
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - test-tutorial
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - test-tutorial      
  
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3312:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - test-tutorial      
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - test-tutorial
    ports:
      - "8085:80"

networks:
  test-tutorial:
    external: true

volumes:
  db-data:

